with Ada.Containers.Vectors;

package Cyk is

   -- Domain-specific types
   subtype Non_Terminal is Character range 'A' .. 'Z';
   subtype Terminal is Character;

   -- Production rule: A -> a (Terminal production)
   type Terminal_Rule is record
      LHS   : Non_Terminal;
      RHS_T : Terminal;
   end record;

   -- Production rule: A -> B C (Binary non-terminal production)
   type Binary_Rule is record
      LHS   : Non_Terminal;
      RHS_1 : Non_Terminal;
      RHS_2 : Non_Terminal;
   end record;

   package Terminal_Rule_Vectors is new Ada.Containers.Vectors
     (Index_Type => Positive, Element_Type => Terminal_Rule);

   package Binary_Rule_Vectors is new Ada.Containers.Vectors
     (Index_Type => Positive, Element_Type => Binary_Rule);

   -- Context-Free Grammar in Chomsky Normal Form (CNF)
   type Grammar is record
      Start_Symbol   : Non_Terminal;
      Terminal_Rules : Terminal_Rule_Vectors.Vector;
      Binary_Rules   : Binary_Rule_Vectors.Vector;
   end record;

   -- Exceptions
   Invalid_Grammar : exception;
   Invalid_Input   : exception;

   -- Subprogram Variants and Helpers

   -- Variant 1: Basic Recognition (CYK Membership Test)
   -- Returns True if Input_String can be generated by Grammar G, False otherwise.
   function Recognize (G : Grammar; Input_String : String) return Boolean
     with Pre  => G.Terminal_Rules.Length > 0 or else G.Binary_Rules.Length > 0,
          Post => True;

   -- Variant 2: Parse Tree Count (Ambiguity / Combinatorial Count)
   -- Returns the total number of distinct parse trees for Input_String under Grammar G.
   function Count_Parse_Trees (G : Grammar; Input_String : String) return Natural
     with Pre  => Recognize (G, Input_String),
          Post => Count_Parse_Trees'Result > 0;

   -- Variant 3: Parse Derivation Reconstruction
   -- Returns a bracketed parse string representing the derivation structure.
   function Parse_To_String (G : Grammar; Input_String : String) return String
     with Pre  => Recognize (G, Input_String),
          Post => Parse_To_String'Result'Length > 0;

   -- Helper / Validation: Checks if grammar strictly adheres to Chomsky Normal Form (CNF)
   function Is_In_Chomsky_Normal_Form (G : Grammar) return Boolean
     with Pre  => True,
          Post => True;

end Cyk;
