with Ada.Strings.Unbounded;
use Ada.Strings.Unbounded;

package body Cyk is

   type NT_Set is array (Non_Terminal) of Boolean;
   Empty_Set : constant NT_Set := (others => False);

   --------------------------------------------------------------------------
   -- Variant 1: Recognize
   --------------------------------------------------------------------------
   function Recognize (G : Grammar; Input_String : String) return Boolean is
      N : constant Natural := Input_String'Length;
   begin
      -- Empty strings are not generated by standard CNF grammars unless S -> epsilon,
      -- which is not represented in standard CNF binary/terminal production sets.
      if N = 0 then
         return False;
      end if;

      declare
         type CYK_Table is array (1 .. N, 1 .. N) of NT_Set;
         Table : CYK_Table := (others => (others => Empty_Set));
      begin
         -- Base case: substrings of length 1 (Table(I, I))
         for I in 1 .. N loop
            for Rule of G.Terminal_Rules loop
               if Rule.RHS_T = Input_String (Input_String'First + I - 1) then
                  Table (I, I)(Rule.LHS) := True;
               end if;
            end loop;
         end loop;

         -- Inductive step: substrings of length 2 to N
         for L in 2 .. N loop
            for I in 1 .. (N - L + 1) loop
               declare
                  J : constant Positive := I + L - 1;
               begin
                  for K in I .. (J - 1) loop
                     for Rule of G.Binary_Rules loop
                        if Table (I, K)(Rule.RHS_1) and then Table (K + 1, J)(Rule.RHS_2) then
                           Table (I, J)(Rule.LHS) := True;
                        end if;
                     end loop;
                  end loop;
               end;
            end loop;
         end loop;

         return Table (1, N)(G.Start_Symbol);
      end;
   end Recognize;

   --------------------------------------------------------------------------
   -- Variant 2: Count_Parse_Trees
   --------------------------------------------------------------------------
   function Count_Parse_Trees (G : Grammar; Input_String : String) return Natural is
      N : constant Natural := Input_String'Length;
   begin
      if N = 0 then
         return 0;
      end if;

      if not Recognize (G, Input_String) then
         return 0;
      end if;

      declare
         type Count_Matrix is array (1 .. N, 1 .. N, Non_Terminal) of Natural;
         Counts : Count_Matrix := (others => (others => (others => 0)));
      begin
         -- Base case: length 1
         for I in 1 .. N loop
            for Rule of G.Terminal_Rules loop
               if Rule.RHS_T = Input_String (Input_String'First + I - 1) then
                  Counts (I, I, Rule.LHS) := Counts (I, I, Rule.LHS) + 1;
               end if;
            end loop;
         end loop;

         -- Inductive steps: length 2 to N
         for L in 2 .. N loop
            for I in 1 .. (N - L + 1) loop
               declare
                  J : constant Positive := I + L - 1;
               begin
                  for K in I .. (J - 1) loop
                     for Rule of G.Binary_Rules loop
                        declare
                           C1 : constant Natural := Counts (I, K, Rule.RHS_1);
                           C2 : constant Natural := Counts (K + 1, J, Rule.RHS_2);
                        begin
                           if C1 > 0 and then C2 > 0 then
                              Counts (I, J, Rule.LHS) := Counts (I, J, Rule.LHS) + (C1 * C2);
                           end if;
                        end;
                     end loop;
                  end loop;
               end;
            end loop;
         end loop;

         return Counts (1, N, G.Start_Symbol);
      end;
   end Count_Parse_Trees;

   --------------------------------------------------------------------------
   -- Variant 3: Parse_To_String
   --------------------------------------------------------------------------
   function Parse_To_String (G : Grammar; Input_String : String) return String is
      N : constant Natural := Input_String'Length;
   begin
      if N = 0 or else not Recognize (G, Input_String) then
         raise Invalid_Input;
      end if;

      declare
         type CYK_Table is array (1 .. N, 1 .. N) of NT_Set;
         Table : CYK_Table := (others => (others => Empty_Set));
      begin
         for I in 1 .. N loop
            for Rule of G.Terminal_Rules loop
               if Rule.RHS_T = Input_String (Input_String'First + I - 1) then
                  Table (I, I)(Rule.LHS) := True;
               end if;
            end loop;
         end loop;

         for L in 2 .. N loop
            for I in 1 .. (N - L + 1) loop
               declare
                  J : constant Positive := I + L - 1;
               begin
                  for K in I .. (J - 1) loop
                     for Rule of G.Binary_Rules loop
                        if Table (I, K)(Rule.RHS_1) and then Table (K + 1, J)(Rule.RHS_2) then
                           Table (I, J)(Rule.LHS) := True;
                        end if;
                     end loop;
                  end loop;
               end;
            end loop;
         end loop;

         function Build_Tree (A : Non_Terminal; I, J : Positive) return Unbounded_String is
         begin
            if I = J then
               for Rule of G.Terminal_Rules loop
                  if Rule.LHS = A and then Rule.RHS_T = Input_String (Input_String'First + I - 1) then
                     return To_Unbounded_String ("(" & A & " " & Rule.RHS_T & ")");
                  end if;
               end loop;
            else
               for K in I .. (J - 1) loop
                  for Rule of G.Binary_Rules loop
                     if Rule.LHS = A then
                        if Table (I, K)(Rule.RHS_1) and then Table (K + 1, J)(Rule.RHS_2) then
                           declare
                              Sub1 : constant Unbounded_String := Build_Tree (Rule.RHS_1, I, K);
                              Sub2 : constant Unbounded_String := Build_Tree (Rule.RHS_2, K + 1, J);
                           begin
                              return To_Unbounded_String ("(" & A & " " & To_String (Sub1) & " " & To_String (Sub2) & ")");
                           end;
                        end if;
                     end if;
                  end loop;
               end loop;
            end if;
            return To_Unbounded_String ("(" & A & ")");
         end Build_Tree;

         Result_US : constant Unbounded_String := Build_Tree (G.Start_Symbol, 1, N);
      begin
         return To_String (Result_US);
      end;
   end Parse_To_String;

   --------------------------------------------------------------------------
   -- Helper / Validation: Is_In_Chomsky_Normal_Form
   --------------------------------------------------------------------------
   function Is_In_Chomsky_Normal_Form (G : Grammar) return Boolean is
   begin
      if G.Terminal_Rules.Is_Empty and then G.Binary_Rules.Is_Empty then
         return False;
      end if;
      return True;
   end Is_In_Chomsky_Normal_Form;

end Cyk;
