--------------------------------------------------------------------------------
-- Package: Cyk_Algorithm
-- Description: Implementation of the Cocke-Younger-Kasami (CYK) parsing algorithm
--              in Ada 2023 for Context-Free Grammars in Chomsky Normal Form (CNF).
--              Includes standard recognition, parse tree generation, and
--              weighted/probabilistic parsing variants.
--------------------------------------------------------------------------------

package Cyk_Algorithm is

   -- Domain types with strict typing
   subtype Nonterminal is Character range 'A' .. 'Z';
   subtype Terminal is Character;

   type Input_String is array (Positive range <>) of Terminal;

   type Production_Type is (Binary, Terminal_Prod);

   type Production (Kind : Production_Type := Binary) is record
      LHS : Nonterminal;
      case Kind is
         when Binary =>
            RHS_1 : Nonterminal;
            RHS_2 : Nonterminal;
         when Terminal_Prod =>
            RHS_Terminal : Terminal;
      end case;
   end record;

   type Production_Array is array (Positive range <>) of Production;

   type Grammar (Max_Productions : Natural) is record
      Count       : Natural := 0;
      Start_Sym   : Nonterminal := 'S';
      Productions : Production_Array (1 .. Max_Productions);
   end record;

   -- Parse Tree Types
   type Node_Type is (Terminal_Node, Nonterminal_Node);

   type Parse_Node (Kind : Node_Type := Nonterminal_Node) is record
      Symbol : Nonterminal;
      case Kind is
         when Terminal_Node =>
            Term : Terminal;
         when Nonterminal_Node =>
            Left  : access Parse_Node;
            Right : access Parse_Node;
      end case;
   end record;

   type Parse_Node_Access is access all Parse_Node;

   -- Weighted CYK types
   type Log_Probability is digits 6 range -1.0E38 .. 0.0;

   type Weighted_Production (Kind : Production_Type := Binary) is record
      LHS      : Nonterminal;
      Log_Prob : Log_Probability := 0.0; -- 0.0 = prob 1.0, negative = prob < 1.0
      case Kind is
         when Binary =>
            RHS_1 : Nonterminal;
            RHS_2 : Nonterminal;
         when Terminal_Prod =>
            RHS_Terminal : Terminal;
      end case;
   end record;

   type Weighted_Production_Array is array (Positive range <>) of Weighted_Production;

   type Weighted_Grammar (Max_Productions : Natural) is record
      Count       : Natural := 0;
      Start_Sym   : Nonterminal := 'S';
      Productions : Weighted_Production_Array (1 .. Max_Productions);
   end record;

   -- Exceptions
   Invalid_Grammar : exception;
   Invalid_Input   : exception;
   Grammar_Not_CNF : exception;

   ----------------------------------------------------------------------------
   -- Subprogram 1: Standard CYK Recognition (Variant 1)
   -- Determines if Input can be generated by Grammar G.
   ----------------------------------------------------------------------------
   function Recognize (G : Grammar; Input : Input_String) return Boolean
     with Pre  => G.Count > 0 and then G.Count <= G.Productions'Length
                  and then Input'Length > 0,
          Global => null;

   ----------------------------------------------------------------------------
   -- Subprogram 2: CYK Parse Tree Generation (Variant 2)
   -- Extends the recognizer to construct and return a parse tree if accepted,
   -- or returns null if rejected.
   ----------------------------------------------------------------------------
   function Parse (G : Grammar; Input : Input_String) return Parse_Node_Access
     with Pre  => G.Count > 0 and then G.Count <= G.Productions'Length
                  and then Input'Length > 0,
          Global => null;

   ----------------------------------------------------------------------------
   -- Subprogram 3: Weighted / Stochastic CYK Parsing (Variant 3)
   -- Parses input using weighted CFG, returning the best parse tree and
   -- its total log probability.
   ----------------------------------------------------------------------------
   procedure Parse_Weighted
     (G          : in     Weighted_Grammar;
      Input      : in     Input_String;
      Accepted   :    out Boolean;
      Best_Log_P :    out Log_Probability;
      Root       :    out Parse_Node_Access)
     with Pre  => G.Count > 0 and then G.Count <= G.Productions'Length
                  and then Input'Length > 0,
          Global => null;

   ----------------------------------------------------------------------------
   -- Helper / Utility Subprograms
   ----------------------------------------------------------------------------
   
   -- Validates whether a grammar is in Chomsky Normal Form (CNF)
   function Is_In_CNF (G : Grammar) return Boolean
     with Pre => G.Count <= G.Productions'Length,
          Global => null;

   -- Deallocates a parse tree recursively to prevent memory leaks
   procedure Free_Parse_Tree (Node : in out Parse_Node_Access);

   -- Helper to serialize parse tree for inspection in tests
   function Tree_ToString (Node : Parse_Node_Access) return String;

end Cyk_Algorithm;
